FROM osrm/osrm-backend

WORKDIR /data

RUN apt-get update && apt-get install -y python3-pip && pip install gdown

RUN gdown https://drive.google.com/uc?id=1KiiaMTAZUWTI_wLUPxmz-E5ttaXVaQAT -O osrm-foot.tgz \
    && tar -xzf osrm-foot.tgz && rm osrm-foot.tgz

EXPOSE 5000

CMD ["osrm-routed", "--algorithm", "ch", "/data/volga-fed-district-latest.osrm"]

